### ISSUE TITLE
logical for isfolder shim may be wrong

### ISSUE THREAD

**Issue by cbm755** [apjanke/octave-packajoozle#38]
On Octave 5.1.0 I get:
```
warning: function /home/cbm/.local/share/octpkgs/5.1.0/packajoozle-0.1.0/shims/pre-5.0/isfolder.m shadows a core library function
```
Probably this is a meaningless warning and you only actually use it on old Octave but its still a scary warning to see...

**Comment by apjanke** [comment]
That's weird. It's not happening for me.

```
>> ver
----------------------------------------------------------------------
GNU Octave Version: 5.1.0 (hg id: d05d6eebde10 + patches)
Octave.app Version: 5.1.0-beta2
GNU Octave License: GNU General Public License
Operating System: Darwin 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
----------------------------------------------------------------------
no packages installed.
>> addpath('~/local/repos/octave-packajoozle/inst')
>> path

Octave's search path contains the following directories:

.
/Users/janke/local/repos/octave-packajoozle/inst/shims/all
/Users/janke/local/repos/octave-packajoozle/inst
/Users/janke/Dropbox/computer/data/Documents/octave
/Applications/Octave-5.1.0.app/Contents/Resources/usr/Cellar/octave-octave-app@5.1.0/5.1.0/share/octave/site/m
```

The test for the pre-5.0 shims is `compare_versions (version, "5.0.0", "<")`. What do you get when you run that?

```
>> compare_versions (version, "5.0.0", "<")
ans = 0
```

**Comment by apjanke** [comment]
Okay, I see this too on Octave 5.1.0, but only when installing from the dist tarball, not just when putting the repo on the path.

```
>> pkg install packajoozle-0.1.0.tar.gz
/var/folders/_4/9mx5ryp52bb_z6drbcbrhwl40000gn/T/octave-help-dNyqsR:418: unknown command `1'
/var/folders/_4/9mx5ryp52bb_z6drbcbrhwl40000gn/T/octave-help-mxOElb:415: unknown command `1'
warning: function /Users/janke/Library/Application Support/Octave.app/5.1.0/pkg/packajoozle-0.1.0/shims/pre-5.0/isfolder.m shadows a core library function
>> ver
----------------------------------------------------------------------
GNU Octave Version: 5.1.0 (hg id: d05d6eebde10 + patches)
Octave.app Version: 5.1.0-beta2
GNU Octave License: GNU General Public License
Operating System: Darwin 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
----------------------------------------------------------------------
Package Name  | Version | Installation directory
--------------+---------+-----------------------
 packajoozle *|   0.1.0 | /Users/janke/Library/Application Support/Octave.app/5.1.0/pkg/packajoozle-0.1.0
>>
```

But it doesn't actually end up doing the shadowing. That shims dir is not on the path, and isfolder is still the Octave one.

```
>> which isfolder
'isfolder' is a function from the file /Applications/Octave-5.1.0.app/Contents/Resources/usr/Cellar/octave-octave-app@5.1.0/5.1.0/share/octave/5.1.0/m/miscellaneous/isfolder.m
>>
```

Maybe what's happening is that the `pkg install` process is temporarily cd-ing into subdirs in the distribution, or temporarily adding them to the path.

**Comment by cbm755** [comment]
This suggests to me that this isn't the best shim, maybe its better to just
```
if compare_versions (OCTAVE_VERSION (), '5.0.0', '<'))
  isdir
else
  isfolder
end
```
Its only for another year or two anyway.

**Comment by apjanke** [comment]
You mean create a separate wrapper function that's not named `isfolder` or `isdir` and use that?

I kind of like the compatibility-shim mechanism; it'll allow me to support older versions of Octave without having to use customized functions for everything.

> Its only for another year or two anyway.

But old versions of Octave stick around for a while in user land. There are people out there still using 4.2.

**Comment by apjanke** [comment]
Okay, I'm convinced, actually. Even if this is due to less-than-ideal behavior of Octave and `doc_cache_create`, that's not going to be fixed in the releases of Octave that are already out there. And I want to be back-compatible to Octave 4.4, and that warning is unacceptable.

I'll remove the shim mechanism.

**Comment by apjanke** [comment]
Done in https://github.com/apjanke/octave-packajoozle/commit/06a046219eae1f2363b33f29ca5e05bbd887e0af. The warning's gone for me on Octave 5.1.0.
