### ISSUE TITLE
Octave 4.2.2: fails on doctest-0.7.0.tar.gz

### ISSUE THREAD

**Issue by cbm755** [apjanke/octave-packajoozle#39]
Octave 4.2.2:
```
>> pkj review doctest-0.7.0.tar.gz
parse error near line 281 of file /home/cbm/.local/share/octpkgs/4.2.2/packajoozle-0.1.0/+packajoozle/+internal/PkgReviewer.m

  syntax error

>>> function out = my_basename (file)
           ^

error: called from
    pkj>review_package at line 662 column 12
    pkj at line 389 column 7
```

**Comment by apjanke** [comment]
Sorry, I can't support Octave 4.2.2; I can't get that version installed on my Mac. Added note to README in https://github.com/apjanke/octave-packajoozle/commit/78b5570b8006c1787a7660f0e779145edca6fc6c: Octave 4.4.1 or later is officially required.

Works for me with doctest-0.6.1.tar.gz. Where are you drawing the doctest-0.7.0.tar.gz from?

```
>> pkj review doctest-0.6.1.tar.gz
Installed doctest 0.6.1 from /var/folders/_4/9mx5ryp52bb_z6drbcbrhwl40000gn/T/packajoozle/pkj-review/work-SoqZqy/doctest-0.6.1.tar.gz to user pkg dir
For information about changes from previous versions of the doctest package, run 'news doctest'.
pkj: loading: doctest 0.6.1
Package review passed for doctest-0.6.1.tar.gz.
```

**Comment by cbm755** [comment]
> Octave 4.4.1 or later is officially required.

Put that in DESCRIPTION:
```
Depends: octave (>= 4.4)
```
(I think Mike decided he would usually just put the major version not minor but `>= 4.4.1` should be fine too)

**Comment by cbm755** [comment]
> Where are you drawing the doctest-0.7.0.tar.gz from?

Release candidate from:

https://sourceforge.net/p/octave/package-releases/373/

**Comment by cbm755** [comment]
I don't currently have a 4.4 to test with and it works with 5.1.0 so I'll close for now.

**Comment by apjanke** [comment]
Added to Depends in https://github.com/apjanke/octave-packajoozle/commit/6eeb3362c4bd676530bb45bbfca6ba3e36601200.
