### ISSUE TITLE
pkj review from clone assumes dist goes into target

### ISSUE THREAD

**Issue by cbm755** [apjanke/octave-packajoozle#43]
Should `make dist` put things into `target/foo.tar.gz`?  Doctest and Symbolic both use `tmp/` but of course I could change that if `target` is somehow the standard place...

**Comment by apjanke** [comment]
I don't know enough about the Forge packaging conventions to know if there is a standard place, but `target` is the place I've seen a few packages put it, so that's where I assumed it should go.

I think a standard place will have to be required if we're going to make the release process more automated. Shall we adopt `target` since some packages are already using it?

**Comment by cbm755** [comment]
I would be fine with whatever but `target` isn't meaningful to me personally..  @mtmiller any input on this?

**Comment by mtmiller** [comment]
I find that surprising and would much rather that `make dist` put `foo.tar.gz` in the current directory.

**Comment by cbm755** [comment]
That certainly sounds better than `tmp`!  @apjanke: maybe pkj should allow `{ '/', '/target', '/tmp', ...}` but all are deprecated except `/` and we'll slowly get everyone on board?

Can you make it `warn('found foo in target/foo.tar.gz: this is deprecated, suggest moving dist file to root')`?

**Comment by cbm755** [comment]
Its always annoyed me that `foo-html.tar.gz` isn't versioned: we should change that convention!

**Comment by apjanke** [comment]
Yes, yes, and yes. I'll add this later today.

**Comment by cbm755** [comment]
I like the idea of `pkj` nudging us all toward a standard: "be firm and verbose but forgiving".

**Comment by apjanke** [comment]
I'll expand it to have the notion of warnings in addition to outright failures.

**Comment by apjanke** [comment]
Done in https://github.com/apjanke/octave-packajoozle/commit/8fc6edb9f57e285729dac9cdcf133ebc56d9e1d6.

```
octave:18> pwd
ans = /Users/janke/tmp/octave-forge/repos/octave-doctest
octave:19> pkj review .
tar: Option --mtime=2019-03-23 12:31:42 -0300 is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
Package review failed for ..
Errors:
    Distribution tarball was empty
Warnings:
    Expected dist file doctest-0.7.0.tar.gz not created by 'make dist' in root of repo
  Actual dist file was at tmp/doctest-0.7.0.tar.gz
octave:20>
```

These errors are due to https://github.com/catch22/octave-doctest/issues/216.
