### ISSUE TITLE
pkj install -forge symbolic makes binary directory

### ISSUE THREAD

**Issue by cbm755** [apjanke/octave-packajoozle#60]
Symbolic has no compiled code.  `pkj install -forge symbolic` makes `x86_64-pc-linux-gnu-api-v53+/symbolic-2.7.1/` which is empty.

`pkg install -forge symbolic` does not make empty directories for nonexistent binary files.

**Comment by apjanke** [comment]
Part of me wants to argue that this is just cosmetic – there's no functional effect, right? – but the rest of me recognizes this as a wart. Will fix.

**Comment by apjanke** [comment]
Fixed in https://github.com/apjanke/octave-packajoozle/commit/8cc3c0d05b243534eff3f77e07c76508994abf99, I think. Can you confirm?

**Comment by cbm755** [comment]
It still creates the parent `x86_64-pc-linux-gnu-api-v53+` (which `pkg` does not).  But it doesn't create an empty `doctest-0.6.1` inside it anymore.

I agree this is all cosmetic.

**Comment by apjanke** [comment]
Okay. I'll continue working on the cleanup; it shouldn't create that parent `x86_64-whatever` dir if there's nothing in it.

**Comment by apjanke** [comment]
I think this is related to #61. If we fix that, this should take care of itself.

**Comment by apjanke** [comment]
Fixed in https://github.com/apjanke/octave-packajoozle/commit/a151141124c6f95857c6b2d77afea42a68c51dde. Now, the arch-specific binary directory is only created if oct-files exist in the installed package.
