### ISSUE TITLE
"pkj install io" puts binary files in different place than pkg

### ISSUE THREAD

**Issue by cbm755** [apjanke/octave-packajoozle#61]
On my setup "pkg install -forge io" makes:
```
/home/cbm/.local/share/octpkgs/6.0.0/io-2.4.12/
/home/cbm/.local/share/octpkgs/6.0.0/io-2.4.12/x86_64-pc-linux-gnu-api-v53+/
```

whereas "pkj install -forge io" makes:
```
.local/share/octpkgs/6.0.0/io-2.4.12/
.local/share/octpkgs/6.0.0/x86_64-pc-linux-gnu-api-v53+/io-2.4.12
```

In one case, the binary dir is a subdir in the other it is not.

**Comment by apjanke** [comment]
This goes back to https://github.com/apjanke/octave-packajoozle/issues/50 ("I don't actually understand `pkg prefix`"). There are options to set the prefix and arch-dependent prefix independently. I think what's happening here is that Packajoozle is defaulting the arch-dependent prefix to be a subdir of the main prefix, where what should actually happen is that the arch-dependent prefix should be left as the main prefix, and that should trigger special-case code to create an arch-dependent directory under each individual package.

Will fix. Thanks for the report.

**Comment by mtmiller** [comment]
I see the same, where I do have separate prefixes configured.

Expected, with `pkg`:
* ~/.local/share/octave/5/packages/io-2.4.12
* ~/.local/lib/octave/5/packages/io-2.4.12/x86_64-pc-linux-gnu

Actual, with `pkj`:
* ~/.local/share/octave/5/packages/io-2.4.12
* ~/.local/lib/octave/5/packages/x86_64-pc-linux-gnu/io-2.4.12

**Comment by apjanke** [comment]
Fixed in https://github.com/apjanke/octave-packajoozle/commit/a151141124c6f95857c6b2d77afea42a68c51dde.

`pkj` was handling the arch dir wrong; it thought that the arch went directly below the arch prefix, and then the package name-ver under that, which was backwards. I have corrected it to use the arrangement `<archprefix>/<pkg-ver>/<arch>` like `pkg` does.
